name: Build and Release Container Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (MAJOR.MINOR.PATCH) to tag the image with'
        required: true
        type: string
      dockerfile_name:
        description: 'Dockerfile name from ./images/ directory (e.g., Dockerfile-x-y-z)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name
        id: meta
        run: |
          DOCKERFILE_NAME="${{ inputs.dockerfile_name }}"
          IMAGE_SUFFIX="${DOCKERFILE_NAME#Dockerfile-}"  # strips "Dockerfile-"
          IMAGE_NAME="ghcr.io/openkcm/container-images/${IMAGE_SUFFIX}:v${{ inputs.version }}"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and Publish Multi-Arch Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f container-images/${{ inputs.dockerfile_name }} \
            -t ${{ steps.meta.outputs.image_name }} \
            --push \
            .
